google/internal/externalaccount: create executable credenitals
ScruffyProdigy/oauth2 pull request #1
Opened 2022-04-18 19:47 UTC by ScruffyProdigy

2022-04-19 18:28 UTC, lsirac commented on google/internal/externalaccount/executablecredsource.go
> +func (cs executableCredentialSource) getTokenFromInMemoryCaching() (string, bool) {
We will not be doing in memory caching for the initial launch so we can remove this.

2022-04-19 18:29 UTC, lsirac commented on google/internal/externalaccount/executablecredsource.go
> +func (cs executableCredentialSource) isInteractive() bool {
We can remove this, we don't plan to support interactive mode in Go.

2022-04-19 19:24 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +type subjectTokenResponse struct {
Changed

2022-04-19 19:24 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +func (cs executableCredentialSource) getTokenFromInMemoryCaching() (string, bool) {
Removed

2022-04-19 19:24 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		result["GOOGLE_EXTERNAL_ACCOUNT_INTERACTIVE"] = "0"
Done

2022-04-19 19:24 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +func (cs executableCredentialSource) isInteractive() bool {
Removed

2022-04-19 19:25 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	if output, err := runCommand(ctx, cs.Command, cs.getEnvironment()); err != nil {
My understanding of the golang library is that they create a variable length buffer behind the scenes and grow it as needed.  @codyoss, correct me if I'm wrong here

2022-04-21 00:26 UTC, lsirac commented on google/internal/externalaccount/basecredentials.go
>  // parse determines the type of CredentialSource needed
// Parse determines the type of CredentialSource needed.

2022-04-21 00:26 UTC, lsirac commented on google/internal/externalaccount/executablecredsource.go
> +// runCommand is basically an alias of exec.CommandContext for testing.
// This is an alias of exec.CommandContext for testing.

2022-04-21 00:26 UTC, lsirac commented on google/internal/externalaccount/executablecredsource.go
> +		if result.Code != nil {
Error code and message are required fields when success=false. 

Java snippet:
```
      this.errorCode = (String) json.get("code");
      this.errorMessage = (String) json.get("message");
      if (errorCode == null
          || errorCode.isEmpty()
          || errorMessage == null
          || errorMessage.isEmpty()) {
        throw new PluggableAuthException(
            "INVALID_EXECUTABLE_RESPONSE",
            "The executable response must contain `error` and `message` fields when unsuccessful.");
```

2022-04-21 15:13 UTC, ScruffyProdigy commented on google/internal/externalaccount/basecredentials.go
>  // parse determines the type of CredentialSource needed
I'll add the period at the end, but capitalizing the name of the function in the comment would be confusing for most go developers, and capitalizing the function name itself would be the go equivalent of adding a "public" in front of it.

2022-04-21 15:15 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +// runCommand is basically an alias of exec.CommandContext for testing.
This isn't the only function that's being added for testing and I'd like to keep the formatting of the comments indicating what these are for consistent.  For reference check out basecredentials.go:20

2022-04-21 15:30 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		if result.Code != nil {
Done

2022-04-21 18:05 UTC, lsirac approved these changes
Thanks Ryan!

2022-04-21 18:05 UTC, lsirac commented on google/internal/externalaccount/executablecredsource.go
> +	} else {
You can remove this else statement

2022-04-21 18:33 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	} else {
Normally I'd do that, but `output` is scoped to just the if/else block, and I think it'd be more idiomatic to leave it that way

2022-04-21 20:40 UTC, codyoss requested changes

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +	EXECUTABLE_SUPPORTED_MAX_VERSION = 1
Should this be a const?
I think this can be unexported.
Names should be camelCase.

`executableSupportedMaxVersion`

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +	if ctx.Err() != nil {
No need to check context error here, it will bubble up in the error returned by Output if needed. Just return cmd.Output()

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +func CreateExecutableCredential(ec ExecutableConfig, config *Config, ctx context.Context) (result executableCredentialSource) {
Take a * ExecutableConfig as the first param.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +func CreateExecutableCredential(ec ExecutableConfig, config *Config, ctx context.Context) (result executableCredentialSource) {
ctx should always be the first arg passed to a function.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +		if err == context.DeadlineExceeded {
I don't think you need a separate error for this case.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +		return "", fmt.Errorf("oauth2/google: executable command failed: %v.", err.Error())
You never need to call err.Error() if you are formatting with %v, just pass err.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +		if exitError, ok := err.(*exec.ExitError); ok {
Maybe instead of the special handling of exec error here, this logic should be moved to runCommand and line 185 just return the output of at command.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +var serviceAccountImpersonationCompiler = regexp.MustCompile("https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/(.*@.*):generateAccessToken")
Can you move this to the top of the file.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +var emptyEnv = func() []string {
This is unused.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +		return json.Marshal(executableResponse{
For executableResponse do you want to include omitempty on any of the fields. Or else when this marshalls the value to a string you will see things like `"id_token":null` in your result. If omitempty was on everything you would not see that key show up in the JSON at all.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +	if ecs.Timeout != 30000*time.Millisecond {
nit: in the other file this value is expressed in seconds. Maybe make the two consistent. maybe even a private const.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +func TestMinimalExectuableCredentialGetEnvironment(t *testing.T) {
Typo in func name

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +		t.Errorf("Incorrect environment received.\nExpected: %s\nRecieved: %s", want, got)
Test errors should be in the format of got then want. Is reversed here, there may be other cases in the file as well.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +	if got, want := err.Error(), "Executables need to be explicitly allowed (set GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES to '1') to run."; got != want {
If you are going to be checking for exact error messages it might be worth pulling these out to private vars so you don't have the same text pasted in two spots.

2022-04-21 20:40 UTC, codyoss commented on google/internal/externalaccount/executablecredsource_test.go
> +	if got, want := err.Error(), "Executables need to be explicitly allowed (set GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES to '1') to run."; got != want {
Or just don't check for the text of the error and only the presence of an error.

2022-04-22 17:01 UTC, ScruffyProdigy commented on google/internal/externalaccount/basecredentials.go
> +	Executable ExecutableConfig `json:"executable"`
Done

2022-04-22 17:02 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		return "", errors.New("oauth2/google: Unable to parse response JSON.")
Done

2022-04-22 17:02 UTC, ScruffyProdigy commented on google/internal/externalaccount/basecredentials.go
> +	} else if c.CredentialSource.Executable.Command != "" {
Done

2022-04-22 17:02 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	return "", errors.New("Executable returned unsupported token type.")
Done

2022-04-22 17:02 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	EXECUTABLE_SUPPORTED_MAX_VERSION = 1
Done

2022-04-22 17:02 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource_test.go
> +		return json.Marshal(executableResponse{
Done

2022-04-22 17:02 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource_test.go
> +	if ecs.Timeout != 30000*time.Millisecond {
Done

2022-04-22 17:03 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource_test.go
> +func TestMinimalExectuableCredentialGetEnvironment(t *testing.T) {
Fixed

2022-04-22 17:03 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource_test.go
> +		t.Errorf("Incorrect environment received.\nExpected: %s\nRecieved: %s", want, got)
Done

2022-04-22 17:04 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource_test.go
> +	if got, want := err.Error(), "Executables need to be explicitly allowed (set GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES to '1') to run."; got != want {
I think it would be a good idea to make sure the correct errors get returned.  I've refactored to avoid duplication here

2022-04-22 17:38 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +func CreateExecutableCredential(ec ExecutableConfig, config *Config, ctx context.Context) (result executableCredentialSource) {
Whoops, missed these comments. Fixed

2022-04-22 17:38 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +func CreateExecutableCredential(ec ExecutableConfig, config *Config, ctx context.Context) (result executableCredentialSource) {
Fixed

2022-04-22 17:39 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		if err == context.DeadlineExceeded {
Whoops, missed these comments.  Fixed

2022-04-22 17:39 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		if exitError, ok := err.(*exec.ExitError); ok {
Fixed

2022-04-22 17:48 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	if ctx.Err() != nil {
Github's format is confusing me.   Somehow I keep missing comments

2022-04-22 17:48 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +var serviceAccountImpersonationCompiler = regexp.MustCompile("https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/(.*@.*):generateAccessToken")
Moved

2022-04-22 17:48 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource_test.go
> +var emptyEnv = func() []string {
Removed

2022-04-22 17:48 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		return "", fmt.Errorf("oauth2/google: executable command failed: %v.", err.Error())
Fixed

2022-04-22 21:55 UTC, lsirac commented on google/internal/externalaccount/executablecredsource.go
> +	if ec.TimeoutMillis == 0 {
Need to validate that the specified timeout is between [5s, 120s] somewhere

2022-04-22 22:22 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	if ec.TimeoutMillis == 0 {
Fixed

2022-04-25 15:55 UTC, codyoss requested changes
Just a couple more nits, else looks good. Thanks for all of the changes!

2022-04-25 15:55 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +	return errors.New("oauth2/google: Executables need to be explicitly allowed (set GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES to '1') to run")
nit: `oauth2/google: executables`...

Same for two below as well.

2022-04-25 15:55 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +	return errors.New("oauth2/google: Invalid `timeout_millis` field. Executable timeout must be between 5 and 120 seconds.")
nit: remove trailing period. Same for error below.

2022-04-25 15:55 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +		return []byte{}, timeoutError()
nit: for these error cases return nil as the first returned value.

2022-04-25 15:55 UTC, codyoss commented on google/internal/externalaccount/executablecredsource.go
> +	TokenType      *string `json:"token_type,omitempty"`
Now that you are using omit empty I don't think we need the `*string` types any more. Can be changed to `string`.  The only time you need to worry and make things pointer type is if the default value of the type also has meaning for a particular field. For instance in the case of bools, `false` is a legit value to send to an API, so we use the type `*bool`.

2022-04-25 16:35 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	return errors.New("oauth2/google: Executables need to be explicitly allowed (set GOOGLE_EXTERNAL_ACCOUNT_ALLOW_EXECUTABLES to '1') to run")
Done!

2022-04-25 16:35 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	return errors.New("oauth2/google: Invalid `timeout_millis` field. Executable timeout must be between 5 and 120 seconds.")
Done!

2022-04-25 16:35 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +		return []byte{}, timeoutError()
Done!

2022-04-25 16:35 UTC, ScruffyProdigy commented on google/internal/externalaccount/executablecredsource.go
> +	TokenType      *string `json:"token_type,omitempty"`
Done!

2022-04-25 17:18 UTC, codyoss approved these changes
Thanks, LGTM

2022-04-25 18:54 UTC, merged